version: '3.7'

networks:
  prometheus-test:
    driver: bridge

services:
  api:
    build: ./api
    networks:
      - prometheus-test
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:v2.12.0
    volumes:
      - './prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml'
    networks:
      - prometheus-test
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:6.4.1
    networks:
      - prometheus-test
    ports:
      - 3000:3000
